version: "3.9"

services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-api
    ports:
      - "4000:4000"
    env_file:
      - ./devforces-backend/.env
    depends_on:
      - redis

  websocket:
    build:
      context: ./devforces-backend
      dockerfile: Dockerfile
    container_name: websocket-server
    command: node dist/ws/ws.server.js
    ports:
      - "8080:8080"
    env_file:
      - ./devforces-backend/.env
    depends_on:
      - redis

  worker:
    build:
      context: ./devforces-backend
      dockerfile: Dockerfile.worker
    container_name: worker
    env_file:
      - ./devforces-backend/.env
    depends_on:
      - redis

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"